// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop.Authentication;

#nullable disable

namespace ShopAPI.Migrations
{
    [DbContext(typeof(TokenBlacklistDBContext))]
    partial class TokenBlacklistDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("Shop.Models.DB.TokenBlacklist", b =>
                {
                    b.Property<string>("Token")
                        .HasColumnType("TEXT");

                    b.HasKey("Token");

                    b.ToTable("TokenBlacklists");
                });
#pragma warning restore 612, 618
        }
    }
}
