# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  shopapi:
    image: shopapi
    build:
      context: .
      dockerfile: ShopAPI/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5143:5143
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw
